#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.3.7f1_9e14d22a41bb"
#define UNITY_VERSION_FULL_NICE "2018.3.7f1 (9e14d22a41bb)"
#define UNITY_VERSION_BLD 10360018
#define UNITY_VERSION_DATE 1551288646
#define UNITY_VERSION_WIN "2018.3.7.10360018"
#define UNITY_VERSION_BRANCH "2018.3/release"
